# Generated by Django 4.0.4 on 2022-04-27 00:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('document_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('card_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('time', models.TimeField()),
                ('owner_name', models.CharField(max_length=256)),
                ('store_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
